update

diff --git a/dev/utilities/bash/partials/strict-mode b/dev/utilities/bash/partials/strict-mode
--- a/dev/utilities/bash/partials/strict-mode
+++ b/dev/utilities/bash/partials/strict-mode
@@ -1,6 +1,27 @@
 #!/usr/bin/env bash
+# {@see https://o5p.me/pnUV7g}.
 
 set -o  nounset;
 set -o  errexit;
 set -o errtrace;
 set -o pipefail;
+
+function stack_trace() {
+	local last_command_status_code=$?;
+	set +o xtrace; # {@see https://o5p.me/8eGn9c}.
+	local exit_status_code="${1:-1}";
+
+	echo '----------------------------------------------------------------------';
+	echo 'Error in '"${BASH_SOURCE[1]}"':'"${BASH_LINENO[0]}";
+	echo '`'"${BASH_COMMAND}"'` exited with status `'"${last_command_status_code}"'`.';
+
+	if [[ ${#FUNCNAME[@]} -gt 2 ]]; then
+		echo 'Stack Trace:';
+		for ((_i=1; _i < ${#FUNCNAME[@]}-1; _i++)); do
+			echo " ${_i}: ${BASH_SOURCE[${_i}+1]}:${BASH_LINENO[${_i}]} ${FUNCNAME[${_i}]}(...)";
+		done;
+	fi;
+	echo 'Exiting with status `'"${exit_status_code}"'`.';
+	exit "${exit_status_code}";
+};
+trap stack_trace ERR;
